[platformio]
default_envs = home

[env]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
lib_deps =
  jgromes/RadioLib@^7.1.2

[env:home]
build_flags =
  -DROLE_HOME=1
lib_deps =
  ${env.lib_deps}
  knolleary/PubSubClient@^2.8

[env:mail]
build_flags =
  -DROLE_MAIL=1

[env:hello]
build_flags =
  -DTEST_HELLO=1
